highlighter: rouge
relative_permalinks: false
url: https://redolfi-unibs.github.io/
title: redolfi@unibs
slogan: PAJC & EPS Official Site!
description: PAJC & EPS Official Site
google_analytics_id: 00-0000-000
exclude: ["CNAME", "README", "bin", "build.xml"]
permalink: /news/:year/:month/:day/:title

news: Gli esiti dell'appello del 16 giugno saranno pubblicati su questo sito il 23 giugno.

author :
  name : Massimiliano Redolfi
  email : massimiliano.redolfi@unibs.it
  github : redolfi-unibs


project:
  name: REDOLFI-UNIBS
  github: redolfi-unibs
theme: jekyll-theme-architect

defaults:
  - scope:
      path: "assets/esiti_eps"
    values:
      esito_eps: true
  - scope:
      path: "assets/esiti_pajc"
    values:
      esito_pajc: true


